# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.6@sha256:61c1806d7594b0bb3e5247709f6db770f3762ddf994545f1c172dc19924a0f7f
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - cache-{{ checksum "Pipfile.lock" }}
            - cache-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .venv
            pip install --user pipenv
            pipenv sync --dev

      - save_cache:
          key: cache-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local
            - ~/.cache

      - run:
          name: run tests
          command: |
            pipenv run flake8 bamboo_crawler tests
            export AWS_ACCESS_KEY_ID='1234'
            export AWS_SECRET_ACCESS_KEY='5678'
            pipenv run python setup.py test
            pipenv run python setup.py sdist bdist_wheel
            pipenv run twine check dist/*

      - store_artifacts:
          path: test-reports
          destination: test-reports
